### ISSUE TITLE
Missing ConvexDecomposition.obj and other compile issues

### ISSUE THREAD

**Issue by LeandroMorus** [mattleibow/jitterphysics#13]
I guess your .gitignore didn't let you push that file:

`*.obj`

I took the one from HACD folder. But still couldn't compile anything on VS 2012.
Jitter.Portable won't recognize the System namespace.
When switching it with Jitter, JitterDemo won't recognize "Xna" in Microsoft namespace.
I'm new to monogame, so I'm going back to pure XNA for now.

I suggest a clean test from a git pull to check whether the issue is in my system or in repo.

**Comment by mattleibow** [comment]
You can use the NuGet directly, then you don't need to compile: https://www.nuget.org/packages/JitterPhysics/

**Comment by LeandroMorus** [comment]
Hi.
Actually, I need to compile because I have made several changes to code.

Some of them to customize the engine, and some to apparently try to fix possible bugs.
When I get back to project, I'll submit them here for appreciation.
