### ISSUE TITLE
.Net 2.0 Support?

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mattleibow/jitterphysics#2]
```
Because of my upstream game engine only supports .net 2.0, is there any plan to 
provide support for it?, as in jitter i can see it heavily using lingq.
```

Original issue reported on code.google.com by `unexplai...@gmail.com` on 24 Jan 2012 at 8:37

**Comment by mattleibow** [comment]
Since .NET 2.0 is not really supported any more, and .NET 4.6 is the new base standard, I am closing this issue.
