### ISSUE TITLE
Nuget - feature request

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mattleibow/jitterphysics#4]
```
Please add Nuget package.
```

Original issue reported on code.google.com by `dave.hil...@gmail.com` on 21 Oct 2012 at 6:18

**Comment by GangOfPenguins** [comment]
There is a nuget package (0.1.7)

**Comment by mattleibow** [comment]
And now 0.2 with full PCL support. Now this works on iOS, Android, Windows Store and any other .NET platform
